### PR TITLE
Keep side navbar section open on page reload

### LINKED ISSUE #308: Sidebar accordions stay open when clicking on page
Currently the sidenav accordions close after clicking into one of the pages. This should remain open until manually closed, or another accordion is navigated to.

### PR DESCRIPTION
**Pull request by sigalsax**
closes #308 and #333 and #331
This renames sections in the navigation.yml to a more intuitive naming scheme and keeps the side navbar open upon refresh

NOTE:
- [x] the functionality is not applied to 'How to Deploy' section because there is no cover page. When click on 'How to Deploy', it automatically navigates to the 'Using Kubernetes Secrets' subentry. Is this something we want to keep?
- [x] the arrows are automatically pointing to the right (next PR?) and not down, if side navbar accordion is open on page reload

closed: 
screen shot 2018-08-16 at 10 56 10

opened:
screen shot 2018-08-15 at 18 24 35

### CODE REVIEW

**Comment by izgeri** [comment]
@sigalsax did you add an issue for the down arrow? that would be good to fix, but it's ok with me if it's a separate PR

right now if I click Handlers -> MySQL and then try to click the arrow to collapse the handler menu, it doesn't work - I have to click twice. that feels buggy, so we should prioritize fixing that next/soon.

**Comment by sigalsax** [comment]
yeah I made a separate issue for it because this branch has been hanging around for a window and wanted to just push. I will fix the bugginess in a separate PR (:

**Comment by sigalsax** [comment]
TODO: Fix sidenav 'Credential Provider' arrow that falls to next line on screen size change

**Comment by typaulhus** [comment]
@sigalsax I have a fix for the Credential Provider TODO item. I'll get a PR out for that fix today.

**Pull request merged**
