### PR TITLE
fix:ssh: fail without exiting program when server config can not be resolved

### PR DESCRIPTION
**Pull request by doodlesbykumbi**
#### What does this PR do (include background context, if relevant)?
Prevents the Secretless process being terminated when server configuration can not be resolved by SSH handler

Some context:
> Initially, I thought about that for a bit and concluded that it’s just a bug, precisely because I assumed that handlers should never panic. My assumption was grounded in the fact that handlers don’t explicitly panic anywhere nor do they use fatalf. This was the exception.
>
> With that reasoning there wouldn’t be a next time as long as we document clearly that handlers should never panic and that perhaps listeners is when panics might happen because of failed config validation.
>
> But now that I’m here thinking about the UX I wonder if  we might want the whole process to terminate if any given handler is unable to do it’s job (e.g. secret resolution fails). At the moment all handlers log the issue and some terminate the connection to the client (e.g. there’s a presumably unaddressed TODO for the ssh handler to terminate the client connection on errors). An argument can be made for not panicking as much as panicking.
>
> It’d be good to have a consistent error handling stategy

#### What ticket does this PR close?
Connected to [relevant GitHub issues, eg #76]
#### What is the status of the manual tests?
Have you run the following manual tests to verify existing functionality continues to function as expected?
- [ ] Manually tested [K8s CRDs](https://github.com/cyberark/secretless-broker/tree/master/test/manual/k8s_crds)
- [ ] Manually tested [Keychain provider](https://github.com/cyberark/secretless-broker/tree/master/test/manual/keychain_provider)
- [ ] Manually run the [K8s demo](https://github.com/cyberark/secretless-broker/tree/master/demos/k8s-demo)
- [ ] Manually run [Kubernetes-Conjur demo](https://github.com/conjurdemos/kubernetes-conjur-demo) with a local Secretless Broker image build of your branch
- [ ] Manually run the [full demo](https://github.com/cyberark/secretless-broker/tree/master/demos/full-demo) (optional)

If this feature does not have any/sufficent automated tests, have you created/updated a folder in `test/manual` that includes:
- [ ] An updated README with instructions on how to manually test this feature
- [ ] Utility `start` and `stop` scripts to spin up and tear down the test environments
- [ ] A `test` script to run some basic manual tests (optional; if does not exist, the README should have detailed instructions)

### CODE REVIEW

**Comment by jonahx** [comment]
Why was it `Fatalf` previously?

**Comment by doodlesbykumbi** [comment]
@jonahx I'm not sure but it shouldn't be. `Fatalf` causes the whole process to panic.

**Comment by izgeri** [comment]
@doodlesbykumbi should we proceed with this PR? I feel like if the issue would be helped by a better error handling strategy, then maybe that's the right approach to ultimately take, rather than making this small one-off change whose impact is hard to understand.

**Comment by doodlesbykumbi** [comment]
@izgeri I'm going to close this for now. We need to think about a better and more consistent error handling approach. I also have too many dangling PRs

**Pull request closed without merging**
